name: qr_chat
description: "QR chat application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  cloud_firestore: ^5.2.1
  firebase_core: 3.3.0
  firebase_storage: ^12.1.3
  shared_preferences: ^2.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon/app_icon.png
