// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRPCmzn66UX689c6_re-HY4O-DjgAFdZ8',
    appId: '1:694764356299:web:b757e74b7070620798514e',
    messagingSenderId: '694764356299',
    projectId: 'chat-app-505dd',
    authDomain: 'chat-app-505dd.firebaseapp.com',
    storageBucket: 'chat-app-505dd.firebasestorage.app',
    measurementId: 'G-7B9B7HLWQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1T9ojuMhxhabaYJ18ZqlnALsiPPAcEWo',
    appId: '1:694764356299:android:b0ece9b4c3f4de6b98514e',
    messagingSenderId: '694764356299',
    projectId: 'chat-app-505dd',
    storageBucket: 'chat-app-505dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCESlXn3PDXrsEKNTeDg2y3q0TQYLxJkWs',
    appId: '1:694764356299:ios:e03bed34b3fd7e3d98514e',
    messagingSenderId: '694764356299',
    projectId: 'chat-app-505dd',
    storageBucket: 'chat-app-505dd.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCESlXn3PDXrsEKNTeDg2y3q0TQYLxJkWs',
    appId: '1:694764356299:ios:e03bed34b3fd7e3d98514e',
    messagingSenderId: '694764356299',
    projectId: 'chat-app-505dd',
    storageBucket: 'chat-app-505dd.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRPCmzn66UX689c6_re-HY4O-DjgAFdZ8',
    appId: '1:694764356299:web:271634c8a48873ac98514e',
    messagingSenderId: '694764356299',
    projectId: 'chat-app-505dd',
    authDomain: 'chat-app-505dd.firebaseapp.com',
    storageBucket: 'chat-app-505dd.firebasestorage.app',
    measurementId: 'G-3JT41W9PY8',
  );
}
